### ISSUE TITLE
Support multiple studies in SONG configuration

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#140]
- [ ] Specs

**Comment by andricDu** [comment]
Specs should include user stories with expected behavior.

**Comment by junjun-zhang** [comment]
### Use story 1:
As a submitter with write access to multiple studies, I would like to be able to config the SONG client *once* with all studies and related tokens, so that I don't need to supply token at the time running SONG client.

### Use story 2:
As a submitter with write access to multiple studies, I would like to be able to switch between studies easily, so I can submit metadata more efficiently and programmatically (particularly when SONG submission is part of a bioinformatics workflow).

### Use story 3:
As a submitter with write access to multiple studies, I would like to minimize the error submitting Analysis Object belonging to one study to an incorrect study, so I don't need to deal with bad (and maybe hard to catch) consequences including leaking sensitive data to unauthorized users.

**Comment by junjun-zhang** [comment]
To address **user story 1**, we could have the `application` configuration file to record all studies the submitter has access to.

Similar to AWS CLI profiles:
```
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

[user2]
aws_access_key_id=AKIAI44QH8DHBEXAMPLE
aws_secret_access_key=je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY
```
As SONG uses YAML for configuration, it might look like this:
```
client:
  serverUrl: http://142.1.177.84:8080/
  programName: sing
  debug: true
logging.level.org.springframework: OFF
studies:
  - studyId: PACA-CA
     accessToken: my_song_upload_access_token
     default: true
  - studyId: PRCA-CA
     accessToken: my_song_upload_access_token  # it's possible different studies use the same token 
  - studyId: BRCA-CA
     accessToken: my_song_upload_access_token_2
```

**Comment by andricDu** [comment]
I've added user stories described into the wiki on the SONG repo.
