### ISSUE TITLE
Spec for publishing an analysis that was previously suppressed

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#228]
Currently, you can [publish](https://github.com/overture-stack/SONG/blob/develop/song-server/src/main/java/org/icgc/dcc/song/server/service/AnalysisService.java#L283-L299) an analysis even if it was previously suppressed.

1. What is the use case for `suppressed` analyses?
2. How shall this case be handled?

**Comment by junjun-zhang** [comment]
`suppressed` means song submitter (or the admin) does not want data associated with the Analysis Object to be downloadable (even for authorized users).

`published` means the opposite, ie, data in the analysis object can be downloaded (by authorized users).

It could go from `published` to `suppressed` maybe because some issue was found with the data. Then it could go from `suppressed` to  back to `published` again, because submitter verified it again, it was a false alarm. What this means is that `suppressed` could be temporary state.

**Comment by rtisma** [comment]
@junjun-zhang should `suppressed` disable the storage-server from allowing a user to download a file? For instance, if a user wants to download files associated with an analysisId that has the state `suppressed`, should their download continue to happen anyways however show a warning "WARNING: you are downloading suppressed data", or be disabled completely?

**Comment by junjun-zhang** [comment]
@rtisma, personally I feel it should stop the data from being downloaded. It's really depends on real use cases though.

There was also something called `redacted` in GNOS/CGHub, it's meant for the use case where cancer donor withdrew the consent, ie did not want data to be used anymore. In such case, data should be removed.

**Comment by rtisma** [comment]
@junjun-zhang  @andricDu  I think it is best that suppressed remain a "permanent operation" if a User does it. In the future, there will be an admin and user role, where certain endpoints can only be accessed by an admin. In this case, the admin would have access to the endpoint to change an analysis from suppressed to unpublished. the user (which is the only option right now), once an analysis is suppressed, there is no going back.

**Comment by andricDu** [comment]
I don't believe this ticket is relevant anymore.
