### ISSUE TITLE
Can tumour_sample_submitter_id be removed from the VariantCall model?

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#229]
Currently no way to access that information (i.e no getter for that information), however the VariantCall table has the attribute. 

[variantCall schema](https://github.com/overture-stack/SONG/blob/develop/song-server/src/main/resources/schema.sql#L90)

[variantCall java model](https://github.com/overture-stack/SONG/blob/develop/song-server/src/main/java/org/icgc/dcc/song/server/model/experiment/VariantCall.java#L30-L44)

Since there is no usage of the field in any of the code, can it be removed from the database?

**Comment by junjun-zhang** [comment]
The behaviour of `variantCall` and `sequencingRead` should be very similar

There was `sample_id` as foreign key in sequenceRead as well in the design, it's not needed because that relationship is managed in `SampleSet` (as shown [here](https://github.com/overture-stack/SONG/blob/develop/song-server/src/main/resources/schema.sql#L85)). In a similar way, `tumour_sample_submitter_id` can be removed from `variantCall`.

**Comment by rtisma** [comment]
Closing as question was answered. Action item recorded in #230
