### ISSUE TITLE
Preliminary look at converting service to OpenJDK 11

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#353]

**Comment by Fgerthoffert** [comment]
To be merged after SAB

**Comment by rtisma** [comment]
The issue with this is outlined in the following issue
https://github.com/cloudfoundry/uaa/issues/716

essentially, in spring boot 2.1.x, after making a POST request to the `/check_token` endpoint, a check was added for the existence of an `active` key in the POST response. Since check_token predates the spec for the `active` key, this key doesnt exist, and results in an error thrown.

The obvious solution is that the auth server needs to be updated to include this. For now, the jdk upgrade is blocked by this

**Comment by rtisma** [comment]
One small note, when converting a project from jd8 to jdk11, after updating the pom.xml files with the proper versions, ensure everything is building and passing with jdk8 before beginning jdk11 debugging. This way package version update issues (regarless of jdk version) and jdk version issues (for example illegal-access error) are separated.
