### ISSUE TITLE
Same uploaded payload should only be saved once to produce one Analysis Object

### ISSUE THREAD

**Issue by junjun-zhang** [overture-stack/SONG#393]
It's been observed same payload can be saved multiple times, each time a new Analysis Object is created.

Desirable behaviour, one uploaded payload can only be saved once, subsequent save operations (if any) should not have any effect.

**Comment by rtisma** [comment]
It is designed that way based on the original spec. There are 2 scenarios

### Scenario1
If the payload has an `analysisId`, then when you upload the first time you will be given a random unique `uploadId`. If you upload the same payload again but with some fields updated (except for the `analysisId`), the song-server will detect its an update to the original upload, based on the `analysisId` and automatically resolve it to be the same `uploadId` as the first upload. Therefore, 2 or more `save` requests with one `uploadId` will result in an error

### Scenario2
If the payload DOES NOT have an `analysisId`, then after you upload the first time you will be given a random unique `uploadId`. Regardless of updates to any field in the original payload, when the same payload is uploaded, the song-server cannot detect that it was previously uploaded since the `analysisId` field was not originally defined (or empty). As a result, each time you upload the same payload (with an undefined `analysisId` field) you will get a new `uploadId`. This contrasts Scenario1 because subsequent uploads would return the **same** `uploadId` and not a new one like in Scenario2. Since there is a new `uploadId` each time, the `save` command cannot know that the 2 different `uploadIds` are actually the same, so it saves them with different `analysisIds`, thus creating multiple analysis objects.
