### ISSUE TITLE
Song Event Payload: Include whole analysis 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#674]
We would like to include the complete analysis as part of the event issued by Song. 

This means downstream services would have all of the data they need to action on the event, rather than having to reach back out to Song. 

## Expected Outcome
- Song adds Analysis JSON to Kafka Message. 
- This should be backwards compatible as it is adding a new field and not modifying any of the existing

**Comment by blabadi** [comment]
This has backward compatibility concern with Maestro, let's consider doing this by keeping the existing fields and add the new stuff until dependents migrate.

**Comment by hlminh2000** [comment]
I'm not sure I recall this ticket :/

**Comment by rosibaj** [comment]
Blocked by topic compaction discussion:https://github.com/apache/kafka/pull/8103 

- Currently, if we have a replay of all Song published events they are not compacted to the lastest state
- could have some issues if we include the whole analysis and need to replay the whole topic

**Comment by blabadi** [comment]
```could have some issues if we include the whole analysis and need to replay the whole topic```
@rosibaj I don't think point #2 is an issue, including the whole analysis won't change how the replay works for the ingestion nodes, just wanted to clarify that.

**Comment by rosibaj** [comment]
@andricDu @blabadi i am not able to vocalize the reasons for dependency .  Can one of you please add a description as to why this is a dependency.

**Comment by blabadi** [comment]
From what I understood the concern is about the message size which requires compaction since the topic log is kept indefinitely , this is a **current problem for all topics** like weblog too in the rdpc kafka.

the other point that was raised is about the replay that an analysis can go from unpublished to published then suppressed etc, and a new ingestion node will read all these state changes, **but this can also happen with the current message structure**, the payload is irrelevant. that's why I'm saying this ticket doesn't affect replays in ingestion nodes.

**Comment by blabadi** [comment]
that also brings me to a side effect: if an analysis is now suppressed in song, and while replaying there is an event were **it was in published state**, how will workflow ingestion node react when it pulls that analysis from the rdpc gateway to see it is now in suppressed state and that event is basically invalid ?
