### ISSUE TITLE
BUG - SONG Publish in Prod return `500` (access denied) error when api_token is Valid

### ISSUE THREAD

**Issue by lindaxiang** [overture-stack/SONG#776]
## Description
SONG server: https://song.rdpc.cancercollaboratory.org/
Endpoint: PublishAnalysis (https://song.rdpc.cancercollaboratory.org/swagger-ui.html#/Analysis/publishAnalysisUsingPUT)
studyId: TEST-INTL
analysisId: fc64866f-d523-452b-a486-6fd523852bf8 (now in UNPUBLISHED state)
When providing valid api_token, it returns `500` error.

Similar behaviour is also observed in WES prod for job run: 
https://wes.rdpc.cancercollaboratory.org/runs/wes-c58625d6f0814296835a45e6010f89d6

Publish analysis works as expected in RDPC dev and qa. 
Works in submission-song Prod as well.

**Comment by lindaxiang** [comment]
@Buwujiu this is also observed in Dev Song instance. 
SONG server: https://song.rdpc-dev.cancercollaboratory.org/
Endpoint: https://song.rdpc-dev.cancercollaboratory.org/swagger-ui.html#/Analysis/publishAnalysisUsingPUT
studyId: TEST-PR
analysisId: 71beb20a-2ebc-491b-beb2-0a2ebcc91b84 (now in UNPUBLISHED state)
When providing valid api_token, it returns `500` error. (`access_denied`)

**Comment by Buwujiu** [comment]
- Song Dev
  -  fixed by updating ego password. 
Song Prod
   - Problem resolved.
   - Cause for access_denied was due to a limitation in ego where certain passwords were never allowing the application to complete their Basic Auth request. Specifically, passwords that contain the % character.
   - The fix: Jon has updated the password in ego and in the config to remove the character, this fixed the issue.
   - Logged an issue for investigate characters in password:  https://github.com/overture-stack/ego/issues/660
